### PR TITLE
5535 Exclude requisition made from web entries in mSupply

### LINKED ISSUE #5535: Invalid Requisition appears to be created due to Finalised  Supplier Invoice
## Invalid Requisition appears to be created due to Finalised  Supplier Invoice

On Mobile setup, It appears that some Finalised `SI` invoice gets processed by the Mobile and invalid requisition are created.  @ujwalSussol  : looked at the data and reviewed the requisition data to work out the flow.  

Cerb Link:

https://cerb.msupply.org/profiles/ticket/CA-5261-QS/conversation
https://cerb.msupply.org/profiles/ticket/XV-9624-ZT/conversation

### To reproduce

Steps to reproduce the behaviour:

1. Perhaps user Fiji MOH  March 22, 2025 data.
2. On Mobile sync out the `Samabula_pharm` store
3. See Error :  Invalid Requisition are created on current date 
4. See Screenshot

Image

What was observed : 

- We have Finalised `SI` that syncs to the mobile
-  Mobile then created invalid Requisition.

### Expected behaviour

'Si' that is of stock transfer should not create a `Requisition`

### Proposed Solution

Fix the bug

### Version and device info

- App version: 8.6.2

### Additional context

Could be related to `RemoteOrder` being `True`, we faced this issue before :  https://github.com/msupply-foundation/mobile/issues/4387       ( It may not be related )

### PR DESCRIPTION
**Pull request by raviSussol**
Fixes #5535 

## Change summary
- Removed `wp` and `wf` statuses from requisition schema and its related method to stop processing incoming requisitions made from web entries in the mSupply.
- Fixed data linkage between `Transaction` & 'Requisiton` objects they have been broken from #5407 

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Use the built [apk](https://store8.gofile.io/download/web/03f1412e-e1a2-4d0f-9309-89ecaa6dcbbc/mSupplyMobile-8_7_0-universal-release.apk) and install on the tablet and use the mSupply [installers](https://www.dropbox.com/scl/fo/05qk2fibmuhya83gjyadm/AG4NfJEH3gyPFDyyFNjz500?rlkey=yl55kgmfplpmejnyzolpbadon&st=1m00pznf&dl=0) to setup central server.
- [ ] For developers the PR is here : https://github.com/msupply-foundation/msupply/pull/16410
**Brand new mobile setup**
- [ ] Setup any mobile site of Fiji moh with mSupply central server (i.e. use Fiji moh datafile)
- [ ] Note copy Fiji moh mSupply data before you proceed below test cases - you'll need it for other variety of test cases
- [ ] I used `Samabula_pharm` store's site
- [ ] Initialize sync from mSupply to mobile
- [ ] Login to the tablet and goto the supplier requisition and follow test 1
**Mobile upgrade setup**
- [ ] Use you Fiji moh mSupply data from second copy
- [ ] Have a mobile apk version setup lower than `v8.6.8`
- [ ] Setup sync with msupply central server with the above store's site
- [ ] Login to the app and in the Supplier requisition you can now see some blank requisitions
- [ ] Now upgrade the mobile app to `v8.7.0`
- [ ] Login to the app after upgrade and do force sync
- [ ] In the mSupply central server goto the scheduler dashboard window and force run `scheduler_processMessages` scheduler
- [ ] Now in the mobile app again do force sync and follow test 2
- [ ] Now export mobile data. You'll need admin pass `thisisnepal123` enter that and click `Export Data`
- [ ] Open that realm file in realm studio and follow test 3

## Tests
- Test 1
- [ ] Should not display blank or having serial number 0 requisition
- [ ] Also check the customer requisition - should not have any blank or having serial number 0 requisition
- [ ] Please do regression tests related requisitions (both customer and supplier) 
  - [ ] Setup 2 mobile apps and 1 oms site (i.e 1 oms central server with 1 oms remote) and 1 mSupply central server and 1 mSupply remote desktop site
  - [ ] Try creating some invoices (i.e from internal order or supplier requisition or request requisition -> response requisition or customer requisition -> customer invoice or outbound shipment (then via stock transfer) -> supplier invoice or inbound shipment
  - [ ] Do thorough tests on these workflow among OG mobile, oms site, msupply sites and see if there anything gets broken - should be working flawlessly

- Test 2
- [ ] All blank requisitions will be gone in the mobile and requisitions having `wp` status will also be gone from the mSupply
- Test 3
- [ ] In the `Requisition` object goto the `linkedTransaction` field where you can see linked transaction records in it
- [ ] Similarly, in the `Transaction` object goto the `linkedRequisition` field where you can see linked requisition records in there

### CODE REVIEW

**Comment by AnushaUp** [comment]
## Testing
Tested in given APK
Steps to reproduce or otherwise test the changes of this PR:

- [ ] Use the built [apk](https://store10.gofile.io/download/web/9a629ee8-ba0b-4221-8d8c-ced6e715564c/mSupplyMobile-8_7_0-rc1-universal-release.apk) and install on the tablet
- [ ] Setup any mobile site of Fiji moh with mSupply central server (i.e. use Fiji moh datafile)
- [ ] I used `Samabula_pharm` store's site
- [ ] Initialize sync from mSupply to mobile
- [ ] Login to the tablet and goto the supplier requisition and follow test 1

## Tests
- [ ] Should not display blank or having serial number 0 requisition
- [ ] Also check the customer requisition - should not have any blank or having serial number 0 requisition
- [ ] Please do regression tests related requisitions (both customer and supplier) 
  - [ ] Setup 2 mobile apps and 1 oms site (i.e 1 oms central server with 1 oms remote) and 1 mSupply central server and 1 mSupply remote desktop site
  - [ ] Try creating some invoices (i.e from internal order or supplier requisition or request requisition -> response requisition or customer requisition -> customer invoice or outbound shipment (then via stock transfer) -> supplier invoice or inbound shipment
  - [ ] Do thorough tests on these workflow among OG mobile, oms site, msupply sites and see if there anything gets broken - should be working flawlessly

File: src/dataMigration.js
Comment (anildahalsussol) [inline src/dataMigration.js:1]: Makes sense so updating transaction so we dont create any blank requisiton in future and also updating requisition and deleting that too...

File: src/sync/incomingSyncUtils.js [hunk 1]
```diff
@@ -675,19 +675,21 @@ export const createOrUpdateRecord = (database, settings, recordType, record) =>
...
-      if (!status) {
-        status = STATUSES.translate(record.status, EXTERNAL_TO_INTERNAL);
-      }
-      if (record.periodID) {
-        period = database.getOrCreate('Period', record.periodID);
-      }
+      if (record.store_ID !== settings.get(THIS_STORE_ID)) break; // Not for this store
+
+      const status = REQUISITION_STATUSES.translate(record.status, EXTERNAL_TO_INTERNAL);
+      if (!status) break; // Must be a requisition status, either 'suggested' or 'finalised'
```
Comment (anildahalsussol) [inline src/sync/incomingSyncUtils.js:681]: Nice so we will not proceed if desired status is not received.

File: src/sync/syncTranslators.js [hunk 2]
```diff
@@ -142,12 +142,11 @@ export const NAME_TYPES = new SyncTranslator({
  */
 class RequisitionStatusTranslator extends SyncTranslator {
   translate(status, direction) {
-    if (['cn', 'wf'].includes(status)) return 'finalised';
+    if (status === 'cn') return 'finalised';
```
Comment (anildahalsussol) [inline src/sync/syncTranslators.js:145]: Nice

**Review by anildahalsussol — APPROVED** [review]
Over all looks good to me.

File: src/dataMigration.js [hunk 3]
```diff
@@ -286,6 +286,45 @@ const dataMigrations = [
       clearNumberSequences(database);
     },
   },
+  {
+    version: '8.7.0',
```
Comment (anildahalsussol) [inline src/dataMigration.js:290]: @raviSussol : I was thinking still WP is mysterious but we are known with another case of creating blank requisition. Is there a place where it can check blank so we dont need to make everytime migrate code?

**Comment by ujwalSussol** [comment]
update : was able to set up the Master mobile... 
Now tomorrow will aim to build mobile via this PR.

**Review by ujwalSussol — APPROVED** [review]
approved :   But we do need to do a group test to make sure that daily activities are not messed up.

**Comment by raviSussol** [comment]
> approved : But we do need to do a group test to make sure that daily activities are not messed up.

Yes that would be great to have other functional or regression tests before releasing the new version.
